woowacourse-teams/2025-moment

client/babel.config.js
client/package.json
client/pnpm-lock.yaml
client/public/index.html
client/src/App.tsx
client/src/constants/colors.ts
client/src/constants/routes.ts
client/src/index.tsx
client/src/layout/ui/Layout.styles.ts
client/src/layout/ui/Layout.tsx
client/src/pages/home/index.tsx
client/src/pages/signup/index.tsx
client/src/routes.tsx
client/tsconfig.json
client/webpack.common.js

- close #17 
- 1. 공통 레이아웃(Layout) 컴포넌트 생성 및 Emotion 스타일 분리
- 2. react-router 기반 라우팅 설정 및 Layout을 루트 레이아웃으로 적용
- 3. HomePage, SignupPage 경로 라우팅 구현
- 추후 다른 페이지가 추가될 예정
- 현재 Layout은 기본적인 Navbar와 Main만 포함됨 (헤더/푸터는 추후 추가 가능)

[FEAT] 공통 레이아웃 및 라우터 적용

---

server/src/main/java/moment/auth/application/AuthService.java
server/src/main/java/moment/auth/application/TokenManager.java
server/src/main/java/moment/auth/dto/request/LoginRequest.java
server/src/main/java/moment/auth/infrastructure/JwtTokenManager.java
server/src/main/java/moment/auth/presentation/AuthController.java
server/src/main/java/moment/auth/presentation/AuthenticationPrincipal.java
server/src/main/java/moment/auth/presentation/LoginUserArgumentResolver.java
server/src/main/java/moment/global/config/WebConfig.java
server/src/main/java/moment/global/exception/ErrorCode.java
server/src/main/java/moment/user/application/UserService.java
server/src/main/java/moment/user/dto/request/Authentication.java
server/src/main/java/moment/user/dto/request/LoginUser.java
server/src/main/java/moment/user/dto/response/UserProfileResponse.java
server/src/main/java/moment/user/presentation/UserController.java
server/src/test/java/moment/auth/application/AuthServiceTest.java
server/src/test/java/moment/auth/presentation/AuthControllerTest.java
server/src/test/java/moment/user/presentation/UserControllerTest.java

- close #61 
- 1. LoginArumentResolver를 구현하였습니다.
- 2. 관련된 테스트 코드를 작성하였습니다.
- 3. 토큰을 기반으로 사용자의 프로필을 조회할 수 있는 api를 생성하였습니다.
- 현재 LoginUser는 id만 필드로 가지고 있는데, 혹시 더 필요한 값이 있을까요?
- 3번 작업은 api 테스트 겸 사용할 것이라고 예측되어 작성해보았습니다! (아니면 유감..) 
현재 nickname만 반환하도록 설정하였는데, 추가 필드가 필요할까요 ? 🤔
- 클래스가 각각 적절한 패키지에 분리되었을까요 ?
- 추가된 기능에 알맞은 테스트가 추가되었을까요 ? !

[FEAT] LoginArgumentResolver 기능 구현 및 테스트

---

client/.gitignore
client/src/app/routes/index.tsx
client/src/app/routes/routes.ts
client/src/app/styles/theme.ts
client/src/features/auth/hooks/useLoginForm.ts
client/src/features/auth/types/login.ts
client/src/features/auth/ui/LoginButton.tsx
client/src/features/auth/ui/LoginForm.styles.ts
client/src/features/auth/ui/LoginForm.tsx
client/src/pages/login/index.styles.ts
client/src/pages/login/index.tsx
client/src/shared/ui/input/Input.styles.ts
client/src/widgets/signup/SignupStep.styles.ts
client/src/widgets/signup/SignupStep1.tsx
client/src/widgets/signup/SignupStep2.tsx

- close #87 
- formData: 이메일, 비밀번호 입력값 관리
- error: 폼 에러 상태 관리 (향후 유효성 검사 확장 예정)
- isLoading: 로그인 요청 중 상태 관리
- isDisabled: 버튼 활성화/비활성화 상태 자동 계산
- handleInputChange: 입력 필드 변경 핸들러
- handleSubmit: 폼 제출 핸들러
- 회원가입 및 로그인 Input 컴포넌트를 공용 컴포넌트로 대체하였습니다.
- Input 공용 컴포넌트 스타일 `input.styles.ts` 에서 placeholder color 색상 변경

[FEAT] 로그인 페이지 구현 

---

server/src/main/java/moment/comment/application/CommentQueryService.java
server/src/main/java/moment/comment/application/CommentService.java
server/src/main/java/moment/comment/application/DefaultCommentQueryService.java
server/src/main/java/moment/comment/infrastructure/CommentRepository.java
server/src/main/java/moment/global/exception/ErrorCode.java
server/src/test/java/moment/comment/application/CommentServiceTest.java
server/src/test/java/moment/comment/application/DefaultMomentQueryServiceTest.java
server/src/test/java/moment/comment/infrastructure/CommentRepositoryTest.java

- close #190 
- 1. 모멘트에 이미 코멘트 존재하는 경우 코멘트 등록 시 예외 발생하도록 수정
- 2. 관련 테스트 작성
- 테스트 시나리오에 문제가 없는지 확인 부탁드립니다.

[FIX] 모멘트에 이미 코멘트 존재하는 경우 코멘트 등록 시 예외 발생하도록 수정

---

client/src/app/routes/index.tsx
client/src/pages/home/index.tsx
client/src/pages/notFound/index.styles.ts
client/src/pages/notFound/index.tsx

- close #222 
- **404 에러 페이지 컴포넌트 추가**
- 명확한 404 에러 코드 표시
- 사용자 친화적인 안내 메시지
- 홈으로 돌아가기 버튼 제공
- **라우팅 개선**
- Catch-all route (`*`) 추가로 모든 잘못된 경로 처리
- 기존 라우팅 구조 유지하면서 에러 처리 강화
- **일관된 디자인**
- 프로젝트 테마 색상 활용
- 반응형 중앙 정렬 레이아웃
- 직관적인 사용자 인터페이스
이제 사용자가 존재하지 않는 URL로 접근했을 때:
1. 빈 화면이나 브라우저 기본 에러 대신 친절한 안내 페이지 표시
2. 명확한 상황 설명과 해결 방법 제시
3. 원클릭으로 홈페이지 복귀 가능

[FEAT] 404 에러 페이지 및 라우팅 구현

---

client/src/features/emoji/hooks/useDeleteEmojiMutation.ts
client/src/features/emoji/hooks/useEmojiMutation.ts
client/src/features/emoji/ui/EmojiButton.tsx
client/src/features/moment/ui/MyMomentsCard.tsx
client/src/features/moment/ui/MyMomentsList.tsx
client/src/pages/postComments/index.tsx

- close #219 
- API 연결된 Emoji 데이터에 상태 관리를 적용했습니다. 이에 따라 이제 이모지 데이터가 추가, 삭제될 때 리렌더링되어 즉각적으로 화면에 반영이 됩니다.
- 나의 코멘트 페이지에서 Emoji GET API를 올바르게 연결시켰습니다. 
- Tanstack Query를 처음 쓰다보니 잘 작성한건지 모르겠네요. 이와 관련해서 잘 구현했는지 검토해주시면 감사하겠습니다.
- 추가 설명에 나온대로, 컴포넌트를 분리해서 각각의 이모지를 관리했는데 이 구조가 괜찮은지 봐주시면 감사하겠습니다!
https://github.com/user-attachments/assets/9b7eb0e1-a10b-4ba4-8d2c-3f0b446f3ac7
- 각 모멘트별로 emojis 상태를 관리하고자 했습니다. 따라서 `MyMomentsList`에서 해당 부분을 `MyMomentsCard`로 분리해 각 모멘트 데이터를 props로 넘겨 작업을 진행했습니다.
- 추가적으로 `postComments`에서 Emoji get API를 정상적으로 연결시켰는데, 일단 구현에 신경쓰느라 React 훅 사용 규칙을 위반한건 확인하지 못했네요. 다음 단계에서 수정하거나 내일 바로 수정해보겠습니다. 
- 위반 규칙: 훅은 컴포넌트 최상위에서만 호출 가능 
- 해당 부분은 구두로 얘기한대로 새로 이슈 파서 작업할 예정입니다.

[FEAT] Emoji 데이터 상태 관리 적용

---

.github/workflows/prod-client-cd.yml
client/package.json
client/pnpm-lock.yaml
client/src/index.tsx
client/src/pages/home/index.tsx
client/src/shared/lib/ga/index.ts
client/webpack.common.js

- close #258 
- Google Analytics 4 측정 ID로 GA 초기화
- 특정 페이지 방문 시 GA에 페이지뷰 데이터 전송
- 사용자 액션(클릭, 폼 제출 등)을 GA 이벤트로 전송 (HomePage에서 MyMoment Button에 적용)
- 카테고리, 액션, 라벨, 값 설정 
- react-ga4 라이브러리 사용
- Github Secret에 GA-ID 추가
- 공용 Google 계정을 생성하여 Notion에 기록해두었습니다.

[FEAT] Google Analytics 기능 구현 

---

client/src/app/routes/ProtectedRoute.tsx
client/src/app/routes/index.tsx

- close #240 
인증되지 않은 사용자가 보호된 페이지에 접근할 때 자동으로 로그인 페이지로 리다이렉트하는 기능을 구현하였습니다.
- `useProfileQuery` 훅을 활용한 사용자 인증 상태 확인
- 로딩 상태 처리 및 인증 실패 시 로그인 페이지 자동 리다이렉트
- 현재 페이지 정보를 state로 전달하여 로그인 후 원래 페이지 복귀 가능
- 공개 페이지(홈, 회원가입, 로그인)와 보호된 페이지 분리
- 보호된 페이지들을 ProtectedRoute로 래핑
- 내 모멘트 페이지
- 오늘의 모멘트 작성 페이지  
- 댓글 작성 페이지
- 오늘의 댓글 페이지 및 성공 페이지

[FEAT] Login Redirect 로직 구현 

---

server/src/main/java/moment/user/application/UserService.java
server/src/main/java/moment/user/domain/User.java
server/src/main/java/moment/user/dto/request/NicknameConflictCheckRequest.java
server/src/main/java/moment/user/dto/response/NicknameConflictCheckResponse.java
server/src/main/java/moment/user/presentation/UserController.java
server/src/test/java/moment/comment/domain/CommentTest.java
server/src/test/java/moment/reply/application/EmojiServiceTest.java
server/src/test/java/moment/reply/infrastructure/EmojiRepositoryTest.java
server/src/test/java/moment/user/application/UserServiceTest.java
server/src/test/java/moment/user/domain/UserTest.java
server/src/test/java/moment/user/presentation/UserControllerTest.java

- close #255 
- 닉네임 중복 체크 API 구현
- 닉네임 중복 체크 API 기능 확인 부탁드립니다.
- 닉네임 중복 체크 swagger 예외 관련 문서화 제대로 되어 있는지 확인 부탁드립니다.

[FEAT] 닉네임 중복 체크 API 구현

---

client/src/app/styles/theme.ts
client/src/features/auth/api/checkEmailExist.ts
client/src/features/auth/api/checkNicknameExist.ts
client/src/features/auth/hooks/useCheckEmail.ts
client/src/features/auth/hooks/useCheckNickname.ts
client/src/features/auth/ui/CheckButton.tsx
client/src/features/auth/ui/SignupForm.tsx
client/src/features/auth/utils/validateAuth.test.ts
client/src/features/auth/utils/validateAuth.ts
client/src/shared/utils/formatRelativeTime.ts
client/src/widgets/signup/SignupStep.styles.ts
client/src/widgets/signup/SignupStep1.tsx
client/src/widgets/signup/SignupStep2.tsx

- close #246 
- 회원가입 시 아이디, 닉네임 중복 체크 기능 추가
- 닉네임 유효성 검증 추가
- 타임 스탬프 기준 수정 (UTC -> KR)
- 중복 체크 로직들은 `SignupForm`에서 불러와 각 Step 컴포넌트에 props로 전달했는데요, 이에따라 props 전달 depth가 2단계가 되어서 이부분 괜찮으신지, 혹시 괜찮은 개선안이 있으신지 의견 주시면 좋겠습니다! 개인적으로는 회원가입에만 쓰이는 로직이라 큰 문제는 없을 것 같다고 생각하긴 합니다.
- 중복 체크 로직들은 `SignupForm`에서 불러와 각 Step 컴포넌트에 props로 전달한 이유:
- 회원가입 폼(`SignupForm`)에서 이전, 다음 버튼 섹션과 본문 섹션은 분리되어 있어서 각 Step에서가 아닌 부모로 끌어올라와서 props로 전달했습니다.

[FEAT] 회원가입 시 아이디, 닉네임 중복 체크 로직 추가 & 타임 스탬프 기준 KR로 수정

---

server/src/main/resources/schema.sql

- close #323 
- 1. alter table 중복 실행 시 duplicate column 에러 발생하여 개발 서버에 적용되는 schema.sql에서 alter table 쿼리 제거

[FIX] 개발 서버 schema.sql 내부에 alter table 쿼리 제거

---

server/src/main/java/moment/user/application/UserService.java
server/src/main/java/moment/user/infrastructure/UserRepository.java
server/src/main/java/moment/user/presentation/UserController.java
server/src/test/java/moment/auth/application/AuthServiceTest.java
server/src/test/java/moment/auth/application/GoogleAuthServiceTest.java
server/src/test/java/moment/user/application/UserServiceTest.java
server/src/test/java/moment/user/infrastructure/UserRepositoryTest.java
server/src/test/java/moment/user/presentation/UserControllerTest.java

- close #351 
- 1. 일반 회원가입에서 이메일 중복 확인 시 ProviderType 고려하도록 변경
- 2. 테스트 코드에서 UserRepository 모킹 시 정확히 특정 이메일과 ProviderType을 모킹하도록 변경
- 3. 불필요 테스트 코드 삭제, 테스트 코드 네이밍 수정

[FIX] 일반 회원가입에서 이메일 중복 확인 시 ProviderType 고려하도록 변경

---

client/src/features/auth/api/getRandomNickname.ts
client/src/features/auth/hooks/useCheckEmail.ts
client/src/features/auth/hooks/useCheckNickname.ts
client/src/features/auth/hooks/useRandomNicknameQuery.ts
client/src/features/auth/hooks/useSignup.ts
client/src/features/auth/ui/LoginForm.styles.ts
client/src/features/auth/ui/LoginForm.tsx
client/src/features/auth/ui/SignupForm.tsx
client/src/features/auth/utils/validateAuth.test.ts
client/src/features/auth/utils/validateAuth.ts
client/src/features/comment/ui/TodayCommentWriteContent.tsx
client/src/features/moment/ui/TodayMomentWriteContent.tsx
client/src/pages/collection/CollectionHeader.tsx
client/src/widgets/signup/SignupStep2.tsx

- close #363 
회원가입 프로세스에서 사용자가 닉네임을 직접 입력하는 대신, 서버에서 생성한 랜덤 닉네임을 자동으로 받아와 설정하는 기능을 구현했습니다.
- **MomentRandomNicknameGenerator**: 우주/별자리 테마의 시적인 랜덤 닉네임 생성기 구현
- 형용사 + 연결어 + 명사 조합으로 "꿈꾸는 우주의 시리우스" 형태의 닉네임 생성
- 기존 AlphanumericNicknameGenerator 대신 @Primary로 설정하여 기본 생성기로 사용
- **NicknameGenerateService**: 중복 닉네임 검증 로직과 재시도 메커니즘(최대 5회) 구현
- **GET /users/signup/nickname** API 엔드포인트 추가
- **useRandomNicknameQuery**: React Query를 활용한 랜덤 닉네임 조회 커스텀 훅 구현
- **getRandomNickname**: 랜덤 닉네임 API 호출 함수 구현
- **SignupStep2 컴포넌트**: 
- 컴포넌트 마운트 시 자동으로 랜덤 닉네임 조회
- 닉네임 입력 필드를 disabled 상태로 변경하여 자동 설정된 닉네임 표시
- API 호출 실패 시 에러 메시지 표시
- 닉네임 다시 받기 기능 구현
- 사용자가 닉네임을 고민할 필요 없이 자동으로 생성된 감성적인 닉네임 제공
- 닉네임 중복 검사 과정 자동화로 회원가입 프로세스 간소화
- 일관된 브랜드 톤앤매너를 반영한 닉네임으로 서비스 정체성 강화
- 전반적인 유효성 검사 강화
- 회원가입 Step1에서 유효성 검사 통과 안했는데 다음 …

[FEAT] 회원가입 이메일 자동완성 API 연결 및 로직 수정

---

.github/workflows/dev-server-cd.yml
.github/workflows/dev-server-ci.yml
server/src/main/java/moment/MomentApplication.java

- close #418
- 1. 배포 이미지를 latest 태그가 아닌 artifact에 저장한 커밋 태그로 불러오도록 변경

[BUILD] 배포 이미지 선정 방식 변경

---

server/src/main/java/moment/user/application/MyPageService.java
server/src/main/java/moment/user/domain/Level.java
server/src/main/java/moment/user/dto/response/MyPageProfileResponse.java
server/src/main/java/moment/user/dto/response/UserProfileResponse.java
server/src/main/java/moment/user/presentation/MyPageController.java
server/src/test/java/moment/user/application/MyPageServiceTest.java
server/src/test/java/moment/user/presentation/MyPageControllerTest.java
server/src/test/java/moment/user/presentation/UserControllerTest.java

- close #469 
- 1.마이페이지 프로필 조회 기능 API 구현
- uri 
```
api/v1/my/profile
```
- 응답 json
```
{
"status": 200,
"data": {
"nickname": "mimi",
"level": "METEOR",
"expStar": 100,
"nextStepExp": 200,
"avabilableStar": 90,
"email": "test@gamil.com" 
}
}
```
- 응답 성공 시 Status
- 200 OK
- 응답 실패 시 Status
- 401
- 404
---
마이페이지에서 표시할 유저 프로필 정보를 조회하기 위한 API 입니다.
문서화 또는 반환 값에서 이상이 없는지 확인 부탁드립니다.

[FEAT] MyPage 프로필 조회 api 기능 구현

---

server/src/main/java/moment/reward/application/RewardService.java
server/src/main/java/moment/reward/application/StarRewardService.java
server/src/main/java/moment/reward/infrastructure/RewardRepository.java
server/src/main/java/moment/user/application/MyPageService.java
server/src/main/java/moment/user/dto/response/MyRewardHistoryPageResponse.java
server/src/main/java/moment/user/dto/response/MyRewardHistoryResponse.java
server/src/main/java/moment/user/presentation/MyPageController.java
server/src/test/java/moment/reward/application/StarRewardServiceTest.java
server/src/test/java/moment/reward/infrastructure/RewardRepositoryTest.java
server/src/test/java/moment/user/application/MyPageServiceTest.java
server/src/test/java/moment/user/presentation/MyPageControllerTest.java

- close #472 
- 1. 마이페이지 나의 보상 기록 조회 offset 기반 페이징 처리 구현
- offset 기반으로 페이징 처리하여 마이페이지에서 나의 보장 기록을 조회할 수 있도록 하였습니다.
- uri
```
api/vi/my/reward/history
```
- 요청 파라미터
- pageNum -> 페이지 번호
- pageSize -> 페이지 사이즈
- 응답 json
```
{
"status": 200,
"data": {
"items": [
{
"id": 1,
"changeStar": 5,
"reason": "COMMENT_CREATION",
"createdAt" : "2025-07-21T10:57:08.926954"
},
{
"id": 2,
"changeStar": -5,
"reason": "COMMENT_CREATION",
"createdAt" : "2025-07-21T10:57:08.926954"
}
],
"currentPageNum": 1,
"pageSize": 10,
"totalPages": 2
}
}
``` 
- StarRewardService 에 구현한 getRewardHistoryByUser() 내에서 페이징 조회를 한 후 이를 MyPageService getMyRewardHistory() 내에서 호출 마이페이지 나의 보상 기록 조회 api를 구현하였습니다.
- service간 참조 흐름상 어색한 것이 없는지 확인 부탁드립니다!

[FEAT] 마이페이지 나의 보상 기록 조회 offset 기반 페이징 처리 구현

---

server/src/main/java/moment/global/exception/ErrorCode.java
server/src/main/java/moment/moment/application/MomentService.java
server/src/main/java/moment/moment/domain/PointDeductionPolicy.java
server/src/main/java/moment/moment/dto/response/MomentCreateResponse.java
server/src/main/java/moment/moment/presentation/MomentController.java
server/src/test/java/moment/moment/application/momentServiceTest.java
server/src/test/java/moment/moment/domain/PointDeductionPolicyTest.java
server/src/test/java/moment/moment/presentation/MomentControllerTest.java

- close #466 
기본 모멘트 이외의 리워드를 사용하여 추가 모멘트를 작성(생성)하는 API를 구현하였습니다.
이때 리워드를 차감하여 추가 모멘트를 작성할 수 있는지 확인한 후, 리워드를 차감하여 추가 모멘트를 생성하였습니다.
API 스펙은 아래와 같습니다.
- POST
- `/api/v1/moments/extra`
- cookie: token
- body
```json
{
"content": "이제 레벨3도 끝인건가.."
}
```
- http status: 201
- data
```json
{
"id": 1,
"momenterId": 1,
"createdAt": "2025-07-14T16:24:34Z",
"content": "그니까 끝이다"
}
```

[FEAT] 추가 모멘트 작성 API 구현 및 테스트 코드 작성

---

server/src/main/java/moment/moment/application/MomentService.java
server/src/main/java/moment/moment/dto/response/MyMomentCommentResponse.java
server/src/main/java/moment/moment/dto/response/MyMomentResponse.java
server/src/test/java/moment/moment/application/momentServiceTest.java

- close #468
내 모멘트 모음을 조회할 때 응답 필드를 수정하였습니다.
moment와 comment의 관계가 1:1에서 1:m으로 변경되면서 moment에 달린 comment를 여러건 조회하도록 변경하였습니다.
comment별로 commenter의 닉네임과 레벨을 추가로 반환하였습니다.
emoji -> echo 도메인명의 변경을 진행했습니다.

[FEAT] 내 모멘트 모음 조회 API 수정

---

server/src/main/java/moment/global/exception/ErrorCode.java
server/src/main/java/moment/user/application/UserService.java
server/src/main/java/moment/user/domain/User.java
server/src/main/java/moment/user/dto/request/ChangePasswordRequest.java
server/src/main/java/moment/user/presentation/UserController.java
server/src/test/java/moment/user/application/UserServiceTest.java
server/src/test/java/moment/user/presentation/UserControllerTest.java

- close #476 
- 1. 마이페이지 내 비밀번호 변경  api 구현
- uri
```
api/v1/users/my/password
```
- 요청 json
```
{
“newPassword”: “qwer1234!”,
“checkPassword” : “qwer1234!”
}
```
- 응답
- 200 ok
- 400
- 404
- 비밀번호 변경 시 유효성 검증이 잘 진행되고 있는지 확인 부탁드립니다.
- EMAIL 회원가입이 아닌 경우 예외 발생해야 합니다.
- 새 비밀번호가 기존 비밀번호와 같은 경우 예외 발생해야 합니다.
- 새 비밀번호와 확인 비밀번호가 다른 경우 예외 발생해야 합니다.
- 새 비밀번호와 확인 비밀번호의 양식이 옳지 않은 경우 예외가 발생해야 합니다.

[FEAT] 마이페이지 비밀번호 변경 api 추가

---

server/src/main/java/moment/moment/application/MomentService.java
server/src/main/java/moment/moment/presentation/MomentController.java
server/src/test/java/moment/moment/application/momentServiceTest.java

- close #486 
- 1. 추가 코멘트 작성 API 호출 시 작성 타입 수정
추가 코멘트 작성 API 호출 시 DB에 작성 타입(write_type)을 BASIC으로 저장하고 있어 EXTRA를 저장하도록 변경하였습니다.
그리고 관련된 코드를 검증할 수 있도록 테스트 코드를 보충하였습니다.
- 2. Swagger summary (간단한) 수정
swagger summary가 어색하게 작성된 부분을 수정했습니다.

[FIX] 추가 코멘트 작성 API 호출 시 작성 타입 수정

---

server/src/main/java/moment/global/logging/NoLogging.java
server/src/main/java/moment/global/logging/ServiceLogAspect.java
server/src/main/java/moment/notification/application/SseNotificationService.java

- close #514 
- 1. 서비스 클래스 내에서 사용할 수 있는 로깅 제외 어노테이션 구현했습니다. 
- 2. heartbeat 메서드를 로깅에서 제외했습니다.

[FEAT] heartbeat 메서드 로깅 제외

---

server/src/main/java/moment/global/logging/ControllerLogAspect.java

- close #580 
- 1. 잘못된 RequestBody.class import 수정
- 수정 전 : import io.swagger.v3.oas.annotations.parameters.RequestBody;
- 수정 후 : import org.springframework.web.bind.annotation.RequestBody;
잘못된 import로 인하여 joinpoint 에서 추출한 파라미터에서 선언 중인 Annotation 비교 실패 문제 해결

[FIX] 잘못된 RequestBody.class import 수정

---

client/src/features/comment/api/useSendCommentsMutation.ts
client/src/features/moment/hook/useMomentsExtraMutation.ts
client/src/features/moment/hook/useMomentsMutation.ts

- close #583 
- `useMomentsExtraMutation` 다음 추가
```
queryClient.invalidateQueries({ queryKey: ['profile'] });
queryClient.invalidateQueries({ queryKey: ['my', 'profile'] });
queryClient.invalidateQueries({ queryKey: ['rewardHistory'] });
```
-  `useSendCommentsMutation`, `useMomentsMutation` 다음 추가
```
queryClient.invalidateQueries({ queryKey: ['profile'] });
```
1. 사용가능한 별조각 42 -> 32 적용 확인
https://github.com/user-attachments/assets/7007560a-b737-4368-8150-e7128f53ab96
레벨 아이콘 변화는 등급업을 해봐야 확인할 수 있을 것 같습니다.

[FIX] navBar 프로필, ExtraMoment 캐시 무효화안되는 이슈 수정

---

client/src/features/auth/ui/AuthButton.tsx

- close #591 
모바일에서 마이페이지 클릭 시 navbar 모달 꺼지도록 `useOutsideClick` 코드에 아래 코드로 수정하였습니다.
handler에 `onClick?.();` 코드를 추가하여 해당 핸들러 발생 시 onClick을 호출하여 모달이 꺼지도록 하였습니다.
```tsx
const handleLogoutClick = () => {
logout();
closeDropdown();
onClick?.();
};
const handleMyPageClick = () => {
navigate('/my');
closeDropdown();
onClick?.();
};
```

[FEAT] 모바일에서 마이페이지 클릭 시 navbar 모달 꺼지도록 기능 개선

---

server/src/main/java/moment/reply/dto/request/EchoCreateRequest.java

- close #595 
- 1. 에코 최대 작성 개수 6개로 수정
(DTO 갯수 수정)

[FIX] 에코 최대 갯수 제한 6개로 수정

---

server/src/main/resources/db/migration/mysql/V14__alter_images__mysql.sql
server/src/test/resources/db/migration/h2/V14__alter_images__h2.sql

- close #650 
- 1. 모멘트 이미지, 코멘트 이미지 테이블의 잘못된 외래키 제약조건을 수정한다.

[FIX] 이미지 테이블 외래키 제약조건 수정

---

server/src/main/java/moment/comment/dto/response/MyCommentsResponse.java
server/src/main/java/moment/global/exception/ErrorCode.java
server/src/main/java/moment/moment/dto/request/MomentCreateRequest.java
server/src/main/java/moment/moment/dto/response/MyMomentsResponse.java
server/src/main/java/moment/notification/application/EmailNotificationService.java
server/src/test/java/moment/moment/presentation/MomentControllerTest.java

- close #653 
- 1.  moment 등록 시 tagName 유효성 검사 로직 추가
- tagName 이 null 로 전송되는 경우 예외 발생
- tagName 이 빈 목록으로 전송되는 경우 예외 발생
- tagName 내부에 빈칸을 포함하는 경우 예외 발생
- 2. 리마인드 메일 전송 시간 수정
- 21시로 수정
- 3. 나의 모음집 응답 값 반환 시 List 필드를 배열로 응답되도록 수정 (MyMomentsPageResponse, MyComentsPageResponse

[REFACTOR] moment 등록 시 tagName 유효성 검사 로직 추가 & 리마인드 메일 전송 시간 수정

---

server/src/main/resources/logback-dev.xml

- close #698 
- 1. logback에서 p6spy와 관련한 로그를 잘 수집할 수 있도록 logger 경로를 수정해주었습니다.

[FIX] p6spy 로그 수집 경로 수정

---

client/src/app/layout/ui/Footer.styles.ts
client/src/app/layout/ui/Footer.tsx
client/src/app/layout/ui/Layout.tsx
client/src/features/comment/ui/MyCommentsCard.styles.ts
client/src/features/comment/ui/MyCommentsCard.tsx
client/src/features/comment/ui/TodayCommentForm.styles.ts
client/src/features/comment/ui/TodayCommentForm.tsx
client/src/features/moment/ui/MyMomentsCard.styles.ts
client/src/features/moment/ui/MyMomentsCard.tsx
client/src/features/moment/ui/TodayMomentForm.tsx
client/src/shared/hooks/useShowFullImage.ts

- close #692 
사용자 피드백, QA 기반으로 나온 개선안 작업 진행했습니다.
1. 태그 개수 제한 설정
- 최대 3개만 등록할 수 있도록 수정
2. 이미지 UI 개선
- 기본적으로 80x80 미리보기 이미지가 보이도록 함
- 미리보기 이미지 클릭시 전체 이미지가 큰 화면으로 보이도록 함
3. 오늘의 코멘트, 나의 모음집 UI 개선
- 위 변경사항에 따른 UI 개선
- 나의 모멘트 모달에서 스크롤 디자인 개선
4. Footer 추가
- 카카오 문의하기 추가
전
후
이미지 클릭시
전
후
전
후

[FEAT] 이미지 보기 & 오늘의 코멘트, 나의 모음집 UI 개선, Footer 추가

---

server/src/main/resources/db/migration/mysql/V19__create_comments__mysql.sql
server/src/main/resources/db/migration/mysql/V19__create_comments_mysql.sql
server/src/main/resources/db/migration/mysql/V20__create_comments__mysql.sql
server/src/test/resources/db/migration/h2/V19__create_comments.mysql.sql
server/src/test/resources/db/migration/h2/V19__create_comments__h2.sql

- close #724 
- 1. 쿼리 최적화에 사용되지 않는 인덱스를 삭제하였습니다. 이때 운영 서버에서 해당 인덱스를 외래키 제약에 사용하고 있어, 외래 키 인덱스를 별도로 추가해주었습니다.

[FIX] 불필요 인덱스 삭제 및 해당 인덱스 사용하는 fk 인덱스 별도로 추가

---

client/instrument.js

- close #737 
- 기존엔 개발/운영서버 모두 Sentry가 추적되도록 설정 되어 있어서 이를 분리했습니다.

[FEAT] Sentry 개발/운영서버 환경 명시적 설정
