woowacourse-teams/2025-moment

server/deploy.sh

- close #22 
- 1. docker 배포용 script 작성

[BUILD] docker 배포용 script 작성

---

server/src/main/resources/schema.sql

- close #37 
- 1.emoji 테이블 유니크 제약조건 추가

[CHORE] emoji 테이블 유니크 제약조건 추가

---

server/src/main/java/moment/global/dto/response/SuccessResponse.java

- close #44 
- 1. 성공 응답 dto 구현

[FEAT] 성공 응답 구현

---

server/build.gradle
server/src/main/java/moment/global/exception/ErrorCode.java
server/src/main/java/moment/user/application/UserService.java
server/src/main/java/moment/user/domain/User.java
server/src/main/java/moment/user/dto/request/UserCreateRequest.java
server/src/main/java/moment/user/infrastructure/UserRepository.java
server/src/main/java/moment/user/presentation/UserController.java
server/src/test/java/moment/user/application/UserServiceTest.java
server/src/test/java/moment/user/domain/UserTest.java
server/src/test/java/moment/user/infrastructure/UserRepositoryTest.java
server/src/test/java/moment/user/presentation/UserControllerTest.java

- close #51 
- 1. 회원가입 API를 구현했습니다.
- 2. 해당 API에 대한 테스트 코드를 작성하였습니다.

[FEAT] 회원가입 기능 구현 및 테스트

---

server/src/main/java/moment/user/application/UserQueryService.java
server/src/main/java/moment/user/application/UserQueryServiceImpl.java

[FEAT] 아이디별 유저 조회 기능 구현

---

server/src/main/java/moment/comment/application/CommentQueryService.java
server/src/main/java/moment/comment/application/CommentService.java
server/src/main/java/moment/comment/application/DefaultCommentQueryService.java
server/src/main/java/moment/comment/domain/Comment.java
server/src/main/java/moment/comment/dto/request/CommentCreateRequest.java
server/src/main/java/moment/comment/dto/response/CommentCreateResponse.java
server/src/main/java/moment/comment/infrastructure/CommentRepository.java
server/src/main/java/moment/comment/presentation/CommentController.java
server/src/main/java/moment/global/exception/ErrorCode.java
server/src/main/java/moment/moment/application/MomentQueryService.java
server/src/main/java/moment/moment/domain/Moment.java
server/src/main/java/moment/moment/infrastructure/MomentRepository.java
server/src/test/java/moment/auth/presentation/AuthControllerTest.java
server/src/test/java/moment/comment/application/CommentServiceTest.java
server/src/test/java/moment/comment/application/DefaultCommentQueryServiceTest.java
server/src/test/java/moment/comment/domain/CommentTest.java
server/src/test/java/moment/comment/presentation/CommentControllerTest.java
server/src/test/java/moment/user/presentation/UserControllerTest.java

- close #64 
- 1. Comment 등록 API 구현
- 2. 관련 테스트 작성

[FEAT] Comment 등록 API 개발

---

server/src/main/java/moment/reply/application/DefaultEmojiQueryService.java
server/src/main/java/moment/user/application/DefaultUserQueryService.java
server/src/main/java/moment/user/application/UserQueryServiceImpl.java

- close #78 
- 1. QueryService 구현체 이름 통일 및 UserQueryServiceImpl 구현

[FIX] QueryService 구현체 이름 통일 및 UserQueryServiceImpl 구현

---

.github/workflows/dev-server-cd.yml
server/Dockerfile
server/deploy.sh
server/docker-compose.yml

[CHORE] 배포 자동화 스크립트 임시 추가 및 도커 설정 변경

---

.github/workflows/dev-server-cd.yml
server/src/main/java/moment/global/exception/ErrorCode.java
server/src/main/java/moment/matching/application/MatchingService.java
server/src/main/java/moment/matching/application/RandomMatchingService.java
server/src/main/java/moment/matching/domain/Matching.java
server/src/main/java/moment/matching/domain/MatchingResult.java
server/src/main/java/moment/matching/infrastructure/MatchingRepository.java
server/src/main/java/moment/moment/domain/Moment.java
server/src/main/java/moment/user/application/DefaultUserQueryService.java
server/src/main/java/moment/user/application/UserQueryService.java
server/src/main/java/moment/user/infrastructure/UserRepository.java
server/src/test/java/moment/matching/application/RandomMatchingServiceTest.java

- close #102 
- 1. 랜덤 매칭 알고리즘 구현 : 왕따 문제 발생 가능😢(혼자 매칭 안되기..), 비활성 사용자 필터링 미이행
- 2. 배포 자동화 임시 스크립트 수정 (테스트용)

[FEAT] 랜덤 매칭 알고리즘 구현

---

.github/workflows/dev-server-cd.yml
server/src/main/java/moment/comment/application/CommentService.java
server/src/test/java/moment/comment/application/CommentServiceTest.java

- close #109 
- 1. Comment 리뷰 반영 및 CD 테스트

[REFACTOR] Comment 리뷰 반영 및 CD 테스트

---

server/src/main/java/moment/global/dto/response/ErrorResponse.java

- close #118 
- 1.Swagger Docs 문서 수정 및 ErrorResponse Status 필드 타입 변경

[FIX] Swagger Docs 문서 수정 및 ErrorResponse Status 필드 타입 변경

---

server/src/main/java/moment/moment/application/MomentService.java
server/src/main/java/moment/moment/dto/response/MatchedMomentResponse.java
server/src/main/java/moment/moment/infrastructure/MomentRepository.java
server/src/main/java/moment/moment/presentation/MomentController.java
server/src/test/java/moment/moment/application/momentServiceTest.java
server/src/test/java/moment/moment/infrastructure/MomentRepositoryTest.java
server/src/test/java/moment/moment/presentation/MomentControllerTest.java

- close #120 
- 1. 모맨트 매칭 기능 추가
- 2. 매칭된 모멘트 조회 기능 추가

[FEAT] 모멘트 매칭 및 조회 기능 추가

---

server/src/main/java/moment/comment/application/dto/response/CommentCreateResponse.java

- close #133 
- 1. Comment 등록 시 생성 시간 반환 누락 문제 해결

[FIX] Comment 등록 시 생성 시간 반환 누락 문제 해결

---

.github/workflows/dev-server-cd.yml
.github/workflows/dev-server-ci.yml
server/src/main/java/moment/reply/dto/request/EmojiCreateRequest.java

- close #149 
- 1. CI/CD 설정 구현
- 2. swagger 명세 변경

[BUILD] CI/CD 설정 구현

---

.github/workflows/dev-server-cd.yml
.github/workflows/dev-server-ci.yml
server/src/test/java/moment/comment/presentation/CommentControllerTest.java
server/src/test/java/moment/moment/presentation/MomentControllerTest.java
server/src/test/resources/application-test.yml

[BUILD]  CI/CD 설정 구현

---

server/src/main/java/moment/auth/infrastructure/JwtTokenManager.java
server/src/test/java/moment/auth/presentation/AuthControllerTest.java

- close #160 
- 1. 로그아웃 테스트 수정

[REFACTOR] Auth API 기능 및 테스트 수정

---

server/docker-compose.yml

- close #162 
- 1.docker-compose.yml image 경로 수정

[FIX] docker-compose.yml image 경로 수정

---

.github/workflows/dev-server-cd.yml
server/docker-compose.yml

- close #165 
- 1. CD .yml 설정 수정

[FIX] CD .yml 설정 수정

---

client/src/features/emoji/api/getEmojis.ts
client/src/features/emoji/const/emojiType.ts
client/src/features/emoji/hooks/useEmojisQuery.ts
client/src/features/emoji/type/emoji.ts
client/src/features/emoji/utils/emojiMapping.ts
client/src/pages/postComments/index.tsx

- close #128 
- emojis get API 연결
- 현재 서버단에서 comment API에 id값을 전송해주지 않아서, 서버에 존재하는 id 값인 4를 넣어두었습니다. 해당부분은 추후 commentId값으로 변경하면 되겠습니다.
```tsx
const { data: emojiResponse } = useEmojisQuery(4); 
```
- emojiMapping 함수: 서버로부터 오는 상수 값을 이모지로 매핑할 수 있도록 했습니다.

[FEAT] emojis get API 연결

---

.github/workflows/dev-server-cd.yml
.github/workflows/dev-server-ci.yml
server/docker-compose.yml

- close #174 
- 1.CD .yml 설정 변경

[FIX] CD .yml 설정 변경

---

.github/workflows/dev-server-cd.yml
.github/workflows/dev-server-ci.yml
server/Dockerfile
server/docker-compose.yml
server/src/main/java/moment/MomentApplication.java

[Fix] CI CD 버그 수정

---

.github/workflows/dev-server-cd.yml
server/src/main/java/moment/MomentApplication.java

- close #
- 1. 환경변수 바로 주입하여 명령 사용하도록 변경

[FIX] ci/cd 환경변수 설정변경

---

.github/workflows/dev-server-cd.yml
.github/workflows/dev-server-ci.yml
server/docker-compose.yml
server/src/main/java/moment/MomentApplication.java

[FIX] CI/CD 배포 설정 변경

---

.github/workflows/dev-server-cd.yml
server/src/main/java/moment/MomentApplication.java

[FIX] cd 트리거 수정

---

.github/workflows/dev-server-cd.yml
server/src/main/java/moment/MomentApplication.java

[FIX] cd 설정 변경

---

server/src/main/java/moment/moment/dto/response/MyMomentCommentResponse.java

- close #210
- 1. 내 모멘트 응답에서 사용하는 코멘트 응답에 id를 추가함

[FEAT] 내 모멘트의 코멘트 id 추가

---

server/Dockerfile

- close #00
- 1. DockerFile 환경변수 추가

[FIX] DockerFile 환경변수 추가

---

server/src/main/java/moment/moment/application/MomentService.java
server/src/main/java/moment/moment/dto/response/MyMomentResponse.java
server/src/main/java/moment/moment/infrastructure/MomentRepository.java
server/src/main/java/moment/moment/presentation/MomentController.java
server/src/test/java/moment/moment/application/momentServiceTest.java
server/src/test/java/moment/moment/presentation/MomentControllerTest.java

- close #227 
- 내 모멘트 조회 api 테스트 작성
- 매칭된 모멘트 조회 api 테스트 작성
- 이미 존재하는 Moment api 테스트의 미흡한 부분 추가 
- MomentRepository에서 Id 대신 User로 조회하게 변경

[TEST] Moment 테스트 추가 및 리팩터링

---

server/src/main/java/moment/comment/dto/response/MomentDetailResponse.java

- close #229 
- 1. MomentDetailResponse moment id 추가
MomentDetailResponse moment id 추가

[REFACTOR] MomentDetailResponse moment id 추가

---

server/src/main/java/moment/auth/application/AuthService.java
server/src/main/java/moment/auth/infrastructure/JwtTokenManager.java
server/src/main/java/moment/global/exception/ErrorCode.java
server/src/main/java/moment/global/exception/GlobalExceptionHandler.java
server/src/main/java/moment/moment/domain/Moment.java
server/src/main/java/moment/reply/domain/Emoji.java
server/src/main/java/moment/user/application/UserService.java
server/src/main/java/moment/user/domain/User.java
server/src/test/java/moment/auth/application/AuthServiceTest.java
server/src/test/java/moment/moment/domain/MomentTest.java
server/src/test/java/moment/reply/domain/EmojiTest.java
server/src/test/java/moment/user/domain/UserTest.java

- close #234
- 1. USER_NOT_FOUND로 통일되던 예외 코드 구체화
- 2. 도메인 검증 시 IllegalArgumentException + 예외 메시지 사용하도록 수정
- 3. GlobalExceptionHandler 내 IllegalArgumentException 처리 로직 추가 (추후에 로그 다르게 찍지 않을까 예측하여)

[REFACTOR] 에러 코드 수정

---

client/src/features/moment/ui/TodayMomentForm.tsx
client/src/features/moment/ui/TodayMomentSuccessContent.tsx
client/src/shared/ui/errorBoundary/ErrorBoundary.styles.ts

- close #267 
-  `useCheckMomentsQuery` 에서 백엔드 API 의 response로 `undefined`를 받을 때   <TodayMomentWriteContent/>를 렌더링 하도록 리팩토링하여 오류 수정

[FIX] 오늘의 모멘트 로직 수정

---

server/src/main/java/moment/global/exception/ErrorCode.java
server/src/main/java/moment/moment/application/MomentService.java
server/src/main/java/moment/moment/domain/MomentCreatePolicy.java
server/src/main/java/moment/moment/domain/MomentCreationStatus.java
server/src/main/java/moment/moment/domain/OnceADayPolicy.java
server/src/main/java/moment/moment/dto/response/MomentCreationStatusResponse.java
server/src/main/java/moment/moment/infrastructure/MomentRepository.java
server/src/main/java/moment/moment/presentation/MomentController.java
server/src/test/java/moment/moment/application/momentServiceTest.java
server/src/test/java/moment/moment/infrastructure/MomentRepositoryTest.java
server/src/test/java/moment/moment/presentation/MomentControllerTest.java

- close #245
- 1. 사용자가 오늘 모멘트를 더 이상 작성할 수 있는지 확인하는 기능 구현
- 2. 모멘트를 작성 시, 오늘 모멘트를 더 이상 작성할 수 있는지 확인 후 예외 반환하도록 구현
- 모멘트 작성 가능 여부 정책을 domain에 분류했는데 어떤지 확인해주세요

[FEAT] 오늘의 모멘트를 이미 작성했는지 확인하는 기능 구현 및 테스트

---

client/instrument.js
client/package.json
client/pnpm-lock.yaml
client/src/index.tsx
client/src/shared/ui/errorBoundary/ErrorBoundary.tsx
client/webpack.common.js

- close #291 
- Sentry 기본 세팅 설정
- 기존 ErrorBoundary에 Sentry 추가

[BUILD] Sentry 에러 트래킹 환경 구축

---

client/src/features/moment/ui/MyMomentsList.tsx
server/src/main/java/moment/global/exception/ErrorCode.java
server/src/main/java/moment/moment/application/MomentService.java
server/src/main/java/moment/moment/domain/Moment.java
server/src/main/java/moment/moment/dto/request/MomentCreateRequest.java
server/src/main/java/moment/moment/presentation/MomentController.java
server/src/test/java/moment/moment/domain/MomentTest.java

- close #266 
- 1. dto에 유효성 검증 추가

[FEAT] 모멘트 생성 요청 dto 유효성 검증 추가

---

server/.gitignore
server/src/main/java/moment/global/logging/ServiceLogAspect.java
server/src/main/java/moment/matching/application/RandomMatchingService.java
server/src/main/resources/logback-spring.xml

- close #293 
- 1. Service 로깅 AOP 구현

[FEAT] Service 계층 로깅 구현

---

server/src/main/java/moment/global/logging/ApiLogInterceptor.java
server/src/main/java/moment/global/logging/RepositoryLogAspect.java
server/src/main/resources/application-dev.yml
server/src/main/resources/logback-spring.xml
server/src/test/resources/application-test.yml

- close #296 
- 1. 리포지 토리 sql 로그 기록 기능 구현
- 2. 리포지토리 소요 시간 로그 기록 기능 구현

[FEAT] 레포지토리 로깅 기능 구현

---

server/src/main/java/moment/user/dto/response/UserProfileResponse.java
server/src/test/java/moment/user/presentation/UserControllerTest.java

- close #324 
- 1. 유저 프로필 조회 응답 dto에 포인트 정보 추가

[FEAT] 유저 프로필 조회 응답값 변경

---

server/src/main/java/moment/auth/dto/google/GoogleAccessToken.java
server/src/main/java/moment/auth/dto/google/GoogleUserInfo.java
server/src/main/java/moment/auth/infrastructure/GoogleAuthClient.java
server/src/test/java/moment/auth/application/AuthServiceTest.java
server/src/test/java/moment/auth/application/GoogleAuthServiceTest.java
server/src/test/java/moment/auth/presentation/AuthControllerTest.java
server/src/test/java/moment/comment/presentation/CommentControllerTest.java
server/src/test/java/moment/user/infrastructure/UserRepositoryTest.java

- close #322 
- 1. 구글 로그인 테스트 코드 작성
- 2. AuthController 컨텍스트 비우는 시점 변경
- 3. 기타 스타일 수정

[TEST] 구글 로그인 테스트 코드 작성

---

server/src/main/java/moment/auth/application/AuthService.java
server/src/test/java/moment/auth/application/AuthServiceTest.java

[FIX] 일반 로그인 이메일이 구글 로그인 이메일과 같은 경우 일반 로그인 안되는 오류 수정

---

server/src/main/java/moment/user/dto/request/EmailConflictCheckRequest.java

- close #347 
- 1. 이메일 중복 확인 시 이메일 정규식 수정

[FIX] 이메일 중복 확인 시 이메일 정규식 수정

---

server/src/main/java/moment/MomentApplication.java
server/src/main/java/moment/notification/application/NotificationService.java

[FIX] sse 버그 수정

---

server/src/main/java/moment/comment/application/CommentService.java
server/src/main/java/moment/notification/application/SseNotificationService.java
server/src/main/java/moment/reply/application/EmojiService.java
server/src/test/java/moment/notification/presentation/NotificationControllerTest.java

[FIX] sse를 트랜잭션에서 제외

---

server/src/main/java/moment/comment/application/CommentService.java
server/src/main/java/moment/notification/presentation/NotificationController.java
server/src/main/java/moment/reply/application/EmojiService.java
server/src/main/resources/application-dev.yml
server/src/test/java/moment/notification/application/NotificationServiceTest.java
server/src/test/java/moment/notification/presentation/NotificationControllerTest.java
server/src/test/resources/application-test.yml

[FIX] osiv false 설정 및 sse 활성화

---

.github/workflows/dev-server-cd.yml
.github/workflows/dev-server-ci.yml
server/src/main/java/moment/notification/application/SseNotificationService.java

- close #373 
- 1. ci cd 워크플로우 수정
- 2. 하트비트 수정

[FIX] CI / CD 트리거 수정

---

.github/workflows/dev-server-ci.yml
server/src/main/java/moment/MomentApplication.java

fix: ci 트리거 수정

---

server/src/main/java/moment/comment/domain/Comment.java
server/src/main/java/moment/comment/dto/request/CommentCreateRequest.java
server/src/main/java/moment/comment/presentation/CommentController.java
server/src/main/java/moment/global/exception/ErrorCode.java
server/src/main/java/moment/moment/domain/Moment.java
server/src/main/java/moment/moment/dto/request/MomentCreateRequest.java
server/src/test/java/moment/comment/domain/CommentTest.java
server/src/test/java/moment/moment/domain/MomentTest.java

- close #385 
- 1.Moment, Comment 글자 수 제한 200자로 변경

[REFACTOR] Moment, Comment 글자 수 제한 200자로 변경

---

server/src/main/java/moment/auth/presentation/AuthController.java
server/src/test/java/moment/auth/presentation/AuthControllerTest.java

- close #400
- 1.구글 로그인 성공 시 콜백 함수 반환 URL 수정

[FEAT] 구글 로그인 성공 시 콜백 함수 반환 URL 수정

---

server/build.gradle
server/docker-compose.yml

- close #408
- 1. Flyway MySQL 의존성 추가 및 로컬 실행용 docker-compose.yml 변경

[FIX] Flyway MySQL 의존성 추가 및 로컬 실행용 docker-compose.yml 변경

---

.github/workflows/dev-server-cd.yml
server/src/main/java/moment/MomentApplication.java

- close #415 
- 1. cd 스크립트 'sudo' 권한부여

[FIX] cd 스크립트 권한변경

---

.github/workflows/dev-server-cd.yml
.github/workflows/dev-server-ci.yml
server/src/main/java/moment/MomentApplication.java

- close #418 
- 1. github actions artifact 버전 변경

[FIX] github actions artifact 버전 변경

---

server/src/main/java/moment/MomentApplication.java

- close #418 
- 1. 배포 이미지 선정 방식 변경

[FEAT] 배포 이미지 선정 방식 변경

---

server/src/main/java/moment/MomentApplication.java

- close #418 
- 1.워크플로우 간 아티팩트 공유하도록 main 브랜치 수정

[FIX] 워크플로우 간 아티팩트 공유하도록 main 브랜치 수정

---

.github/workflows/dev-server-cd.yml
server/src/main/java/moment/MomentApplication.java

- close #418 
- 1. ec2 도커 컴포즈 내 태그 전달

[FIX] ec2 도커 컴포즈 내 태그 전달

---

.github/workflows/dev-server-cd.yml
server/src/main/java/moment/MomentApplication.java

- close #418 
- 1. sudo 시 환경변수 전달하도록 변경

[FIX] sudo 시 환경변수 전달하도록 변경

---

.github/workflows/dev-server-rollback.yml

- close #430 
- 1. 필요할 때 이미지 태그를 입력하여 롤백하는 시스템 스크립트 작성

[BUILD] 롤백 스크립트 작성

---

.github/workflows/prod-server-alarm.yml
.github/workflows/prod-server-cd.yml
.github/workflows/prod-server-ci.yml
server/src/main/java/moment/MomentApplication.java

- close #433 
- 1. 운영 서버 CI/CD 스크립트 작성

[BUILD] 운영 서버 CI/CD 스크립트 작성

---

server/src/main/java/moment/global/exception/GlobalExceptionHandler.java

[REFACTOR] 로깅 전략 수정

---

server/src/main/java/moment/comment/application/CommentService.java
server/src/main/java/moment/notification/dto/response/NotificationSseResponse.java
server/src/main/java/moment/reply/application/EchoService.java
server/src/test/java/moment/comment/application/CommentServiceTest.java
server/src/test/java/moment/notification/application/NotificationServiceTest.java
server/src/test/java/moment/reply/application/EchoServiceTest.java

- close #543 
- 1. sse 알림과 연동된 알림 엔티티의 id를 추가했습니다.

[REFACTOR] sse 알림에 id 추가

---

server/src/main/java/moment/auth/application/AuthEmailService.java

- close #546 
- 1. 비밀번호 변경 url에 이메일 파라미터 추가
- 비밀번호 변경시, 사용자에게 이메일을 재입력 받지 않기 위해 쿼리스트링에 추가

[FIX] 비밀번호 변경 url에 쿼리스트링으로 이메일 추가

---

client/src/features/auth/ui/AuthButton.styles.ts
client/src/pages/collection/index.styles.ts
client/src/pages/collection/mycomment/index.tsx
client/src/pages/collection/mymoment/index.tsx
client/src/widgets/navigatorsBar/index.styles.ts
client/src/widgets/navigatorsBar/index.tsx

- close #531 
회의 때 이야기한 내용대로  나만의 모음집 탭, 네비게이션 바 UI 를 수정했습니다.
1. 모음집 탭
- 탭 활성화 여부 UI 구현 - 노란색 글자색, border-bottom 적용 
- 알림 왔을때 UI 개선 - 오른쪽 상단에 노란 점 애니메이션 효과 적용
- 각 모음집 탭 제목 제거
2. 네비게이션 바
- 네비게이션 활성화 여부 UI 구현 - 노란색 글자색 적용
- 닉네임 글자색 노란색 -> 하얀색 수정
https://github.com/user-attachments/assets/195d0028-ad8e-415a-aeff-17e77971f960

[REFACTOR] 나만의 모음집 탭, 네비게이션 바 UI 개선

---

server/src/main/resources/application-dev.yml

- close #573 
- 1. 프론트엔드 개발 사이트 cloudfront 도메인 연결함에 따라 리디렉션 주소 변경

[REFACTOR] 프론트엔드 개발용 사이트 리디렉션 uri 수정

---

server/build.gradle
server/src/main/resources/application-dev.yml
server/src/main/resources/application-prod.yml

- close #575 
- 1. 서버 내부 모니터링을 위한 spring actuator 설정을 추가하였습니다.

[FEAT] spring actuator 설정

---

server/src/main/resources/application-dev.yml
server/src/main/resources/application-prod.yml

- close #575
- 1. cloudwatch namespace 설정을 수정하였습니다.

[FIX] cloudwatch namespace 설정 수정

---

server/build.gradle
server/src/main/resources/application-dev.yml
server/src/main/resources/application-prod.yml

- close #575 
- 1. 라이브러리 최신화에 따른 설정 변경

[CHORE] AWS cloudwatch 지표 수집 라이브러리 및 설정 변경

---

server/src/main/java/moment/notification/application/SseNotificationService.java
server/src/main/resources/application-dev.yml

[FIX] 비동기 타임아웃 무제한 설정

---

client/public/index.html

- close #612
외부에 링크 공유 시 미리보기가 표시되기 위해Open Graph (OG) 태그와 Twitter Card 메타 태그를 `index.html`에 설정하였습니다.
이를 통해 슬랙, 카카오톡, 페이스북 등에서 링크 미리보기가 표시됩니다.

[FEAT] 메타데이터 추가

---

server/src/main/java/moment/global/config/S3Config.java

- close #618 
- 1. S3Presigner 오버라이드 uri 설정 변경

[CHORE] s3Presigner 생성 설정 변경

---

server/build.gradle
server/src/main/java/moment/auth/application/AuthService.java
server/src/main/java/moment/auth/application/GoogleAuthService.java
server/src/main/java/moment/auth/application/TokensIssuer.java
server/src/main/java/moment/auth/domain/Tokens.java
server/src/main/java/moment/auth/presentation/AuthController.java
server/src/test/java/moment/auth/application/AuthServiceTest.java
server/src/test/java/moment/auth/application/GoogleAuthServiceTest.java
server/src/test/java/moment/auth/application/TokensIssuerTest.java
server/src/test/java/moment/auth/presentation/AuthControllerTest.java

- close #713
- 1. 기존 Map으로 관리하던 AccessToken, RefreshToken 쌍을 하나의 객체로 만들었습니다.

[REFACTOR] 토큰 관련 리팩토링 진행

---

server/src/main/resources/db/migration/mysql/V20__create_comments__mysql.sql

- close #724
- 1. 옵티마이저가 인덱스를 선택하도록 조인 컬럼까지 인덱스에 추가해주었습니다.

[REFACTOR] comments 인덱스 수정

---

server/src/main/resources/db/migration/mysql/V20__create_comments_index__mysql.sql
server/src/test/resources/db/migration/h2/V20__create_comments_index__h2.sql

- close #
- 1. 빠른 코멘트 조회를 위한 인덱스를 추가했습니다.

[CHORE] 인덱스 추가

---

server/src/main/java/moment/comment/application/CommentService.java
server/src/main/java/moment/comment/domain/Comment.java
server/src/main/java/moment/comment/dto/response/MyCommentResponse.java
server/src/main/java/moment/comment/dto/response/MyCommentsResponse.java
server/src/main/java/moment/comment/infrastructure/CommentRepository.java
server/src/test/java/moment/comment/presentation/CommentControllerTest.java

- close #754 
- 1. left fetch join을 사용해 삭제된 모멘트는 null로 처리되게 변경했습니다.

[FIX] 나의 코멘트 페이지 페이지네이션 버그 수정

---

client/src/app/layout/ui/StarField.tsx
client/src/features/comment/ui/TodayCommentForm.tsx

- close #760 
- 1. 오늘의 코멘트 문제 해결
- 2. star 반짝이는 주기 속도 감소

[FIX] 오늘의 코멘트 오류 해결

---

server/src/main/java/moment/global/exception/GlobalExceptionHandler.java
server/src/main/resources/logback-spring.xml

- close #
- 1. ERROR 로그 역시 json 포맷팅 되도록 수정
- 2. logback 파일 저장하도록 설정 변경 
- 기존에 콘솔 출력 설정만 존재하고 있었음

[REFACTOR] 로깅 개선

---

server/src/main/resources/logback-spring.xml

- close #
- 1. 로그 정보에서 'version'정보 제거

[REFACTOR] 로그 출력 개선

---

server/src/main/java/moment/global/logging/ApiLogFilter.java
server/src/main/resources/logback-spring.xml

- close #773
- 1. 로그 출력 순서 포맷을 최적화 했습니다.

[REFACTOR] 로그 포맷 최종 개선
